[pytest]
markers =
    slow: marks tests as slow (e.g. require full model training or large datasets)
    fast: marks tests that are fast and use synthetic data
    integration: tests that evaluate the entire API flow
testpaths =
    tests
