"""drop_texto_bruto

Revision ID: 3edd96b86656
Revises: 5b30e05c17e5
Create Date: 2026-10-08 09:48:50.854740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edd96b86656'
down_revision: Union[str, None] = '5b30e05c17e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias') as batch_op:
        batch_op.alter_column('texto_truncado', existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column('texto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias') as batch_op:
        batch_op.add_column(sa.Column('texto', sa.TEXT(), nullable=False))
        batch_op.alter_column('texto_truncado', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
