"""Initial migration

Revision ID: 5b30e05c17e5
Revises: 
Create Date: 2026-10-08 09:44:23.931174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b30e05c17e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version', 'pipeline_version', name='_model_pipeline_uc')
    )
    op.create_index(op.f('ix_modelos_id'), 'modelos', ['id'], unique=False)
    op.create_table('noticias',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hash_texto', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('texto_truncado', sa.Text(), nullable=True),
    sa.Column('modelo_id', sa.BigInteger(), nullable=False),
    sa.Column('prob_suspeita', sa.Float(), nullable=False),
    sa.Column('faixa', sa.String(length=30), nullable=False),
    sa.Column('trunc_pausality', sa.Float(), nullable=False),
    sa.Column('trunc_emotiveness', sa.Float(), nullable=False),
    sa.Column('trunc_diversity', sa.Float(), nullable=False),
    sa.Column('trunc_upper_case_density', sa.Float(), nullable=False),
    sa.Column('trunc_verb_density', sa.Float(), nullable=False),
    sa.Column('trunc_noun_density', sa.Float(), nullable=False),
    sa.Column('trunc_adj_density', sa.Float(), nullable=False),
    sa.Column('trunc_adv_density', sa.Float(), nullable=False),
    sa.Column('trunc_pron_density', sa.Float(), nullable=False),
    sa.Column('link_density', sa.Float(), nullable=False),
    sa.Column('rc_spelling_errors', sa.Float(), nullable=False),
    sa.Column('rc_modal_verbs_density', sa.Float(), nullable=False),
    sa.Column('rc_subj_imp_verbs_density', sa.Float(), nullable=False),
    sa.Column('rc_pron_1_2_sing_density', sa.Float(), nullable=False),
    sa.Column('rc_pron_1_plur_density', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_texto', 'modelo_id', name='_hash_modelo_uc')
    )
    op.create_index(op.f('ix_noticias_hash_texto'), 'noticias', ['hash_texto'], unique=False)
    op.create_index(op.f('ix_noticias_id'), 'noticias', ['id'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('noticia_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('noticia_id', 'client_id', name='uq_noticia_cliente')
    )
    op.create_index(op.f('ix_avaliacoes_client_id'), 'avaliacoes', ['client_id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_index(op.f('ix_avaliacoes_client_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_noticias_id'), table_name='noticias')
    op.drop_index(op.f('ix_noticias_hash_texto'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_modelos_id'), table_name='modelos')
    op.drop_table('modelos')
    # ### end Alembic commands ###
